env:
  TERM: xterm-256color
  WINIT_HIDPI_FACTOR: "1"

window:
  # window position
  # position:
  #   x: 0
  #   y: 0

  # blank space added around the window in pixels
  padding:
    x: 35
    y: 35

  # spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # - full: Borders and title bar
  # - none: Neither borders nor title bar
  decorations: full

  # - Windowed
  # - Maximized
  # - Fullscreen
  startup_mode: Windowed

  # allow terminal applications to change window title
  dynamic_title: false

  # window title
  title: Alacritty

  # window class (linux only)
  class: Alacritty

scrolling:
  # specifying '0' will disable scrolling
  history: 0

  # number of lines the viewport will move
  multiplier: 3

font:
  normal:
    family: Source Code Pro

  bold:
    family: Source Code Pro

  italic:
    family: Source Code Pro

  # point size
  size: 10.0

  # offset is the extra space around each character
  offset:
    x: 0
    y: 2

  # glyph offset determines the locations of the glyphs within their cells
  glyph_offset:
    x: 0
    y: 1

debug:
  # display the time it takes to redraw each frame.
  render_timer: false

  # keep the log file after quitting alacritty.
  persistent_logging: false

  # - None
  # - Error
  # - Warn
  # - Info
  # - Debug
  # - Trace
  log_level: Warn

  # print all received window events.
  print_events: false

  # record all characters and escape sequences as test data.
  ref_test: false

# bold text drawn using the bright color variants
draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '0x383838'
    foreground: '0xe5dbd0'

  normal:
    black:   '0x454545'
    red:     '0xda7c72'
    green:   '0xb8b48a'
    yellow:  '0xdfa883'
    blue:    '0x93b3a3'
    magenta: '0xcc9999'
    cyan:    '0x9fb193'
    white:   '0xf2e7e0'

  bright:
    black:   '0x998f85'
    red:     '0xda7c72'
    green:   '0xb8b48a'
    yellow:  '0xf7d0a2'
    blue:    '0x93b3a3'
    magenta: '0xcc9999'
    cyan:    '0x9fb193'
    white:   '0xe5dbd0'

  # indexed colors include all colors from 16 to 256
  indexed_colors: []

  # selection colors
  selection:
    # text: '0xf0ebdc'
    background: '0x454545'

# specifying a 'duration' of '0' will disable the visual bell
bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xdfa883'

# '0.0' is completely transparent and '1.0' is opaque
background_opacity: 1.0

mouse:
  # time to wait for accepting multiple clicks
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # cursor temporarily hidden when typing
  hide_when_typing: true

  url:
    # when set to 'None', URL launching will be disabled completely
    launcher: xdg-open

    # modifiers that need to be held down for opening URLs when clicking
    modifiers: Control|Shift

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # when set to 'true', selected text will be copied to the primary clipboard
  save_to_clipboard: true

cursor:
  # - ▇ Block
  # - _ Underline
  # - | Beam
  style: Underline

  # render as a hollow box when the window is not focused
  unfocused_hollow: true

# live config reload
live_config_reload: true

# send ESC (\x1b) before characters when alt is pressed
alt_send_esc: true

key_bindings:
  # unset some unwanted key bindings
  - { key: Insert,   mods: Shift,         action: None }
  - { key: Key0,     mods: Control,       action: None }
  - { key: Equals,   mods: Control,       action: None }
  - { key: Add,      mods: Control,       action: None }
  - { key: Subtract, mods: Control,       action: None }
  - { key: Minus,    mods: Control,       action: None }
  - { key: Return,   mods: Alt,           action: None }

  - { key: V,        mods: Control|Shift, action: Paste }
  - { key: C,        mods: Control|Shift, action: Copy  }
