env:
  TERM: xterm-256color
  WINIT_HIDPI_FACTOR: "1"

window:
  # window position
  # position:
  #   x: 0
  #   y: 0

  # blank space added around the window in pixels
  padding:
    x: 35
    y: 35

  # spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # - full: Borders and title bar
  # - none: Neither borders nor title bar
  decorations: full

  # - Windowed
  # - Maximized
  # - Fullscreen
  startup_mode: Windowed

  # window title
  title: Alacritty

  # window class (linux only)
  class: Alacritty

scrolling:
  # specifying '0' will disable scrolling
  history: 0

  # number of lines the viewport will move
  multiplier: 3

  # specifying '0' will disable faux scrolling
  faux_multiplier: 0

  # scroll to the bottom when new text is written to the terminal
  auto_scroll: false

# change the 'it' value in terminfo when altering this setting
tabspaces: 8

font:
  normal:
    family: Source Code Pro

  bold:
    family: Source Code Pro

  italic:
    family: Source Code Pro

  # point size
  size: 10.0

  # offset is the extra space around each character
  offset:
    x: 0
    y: 0

  # glyph offset determines the locations of the glyphs within their cells
  glyph_offset:
    x: 0
    y: 0

debug:
  # display the time it takes to redraw each frame.
  render_timer: false

  # keep the log file after quitting alacritty.
  persistent_logging: false

  # - None
  # - Error
  # - Warn
  # - Info
  # - Debug
  # - Trace
  log_level: Warn

  # print all received window events.
  print_events: false

  # record all characters and escape sequences as test data.
  ref_test: false

# bold text drawn using the bright color variants
draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '0x222222'
    foreground: '0xebd8bb'

  normal:
    black:   '0x3e3e3e'
    red:     '0xe96b56'
    green:   '0xc8bc61'
    yellow:  '0xff9c5c'
    blue:    '0x91c1ae'
    magenta: '0xcf90a1'
    cyan:    '0xa6ca99'
    white:   '0xebdfcc'

  bright:
    black:   '0x998e82'
    red:     '0xe96b56'
    green:   '0xc8bc61'
    yellow:  '0xfcb866'
    blue:    '0x91c1ae'
    magenta: '0xcf90a1'
    cyan:    '0xa6ca99'
    white:   '0xebd8bb'

  # indexed colors include all colors from 16 to 256
  indexed_colors: []

  # selection colors
  selection:
    # text: '0xf0ebdc'
    background: '0x3e3e3e'

# specifying a 'duration' of '0' will disable the visual bell
visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xebdfcc'

# '0.0' is completely transparent and '1.0' is opaque
background_opacity: 1.0

mouse:
  # time to wait for accepting multiple clicks
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # cursor temporarily hidden when typing
  hide_when_typing: true

  url:
    # when set to 'None', URL launching will be disabled completely
    launcher: xdg-open

    # modifiers that need to be held down for opening URLs when clicking
    modifiers: Control|Shift

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # when set to 'true', selected text will be copied to the primary clipboard
  save_to_clipboard: true

# allow terminal applications to change window title
dynamic_title: false

cursor:
  # - ▇ Block
  # - _ Underline
  # - | Beam
  style: Underline

  # render as a hollow box when the window is not focused
  unfocused_hollow: true

# live config reload
live_config_reload: true

# send ESC (\x1b) before characters when alt is pressed
alt_send_esc: true

key_bindings:
  # unset some unwanted key bindings
  - { key: Insert,   mods: Shift,         action: None }
  - { key: Key0,     mods: Control,       action: None }
  - { key: Equals,   mods: Control,       action: None }
  - { key: Add,      mods: Control,       action: None }
  - { key: Subtract, mods: Control,       action: None }
  - { key: Minus,    mods: Control,       action: None }
  - { key: Return,   mods: Alt,           action: None }

  - { key: V,        mods: Control|Shift, action: Paste }
  - { key: C,        mods: Control|Shift, action: Copy  }

  - { key: L,        mods: Control, chars: "\x0c"                            }
  - { key: Home,                    chars: "\x1bOH",        mode: AppCursor  }
  - { key: Home,                    chars: "\x1b[H",        mode: ~AppCursor }
  - { key: End,                     chars: "\x1bOF",        mode: AppCursor  }
  - { key: End,                     chars: "\x1b[F",        mode: ~AppCursor }
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~",     mode: Alt        }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                       }
  - { key: PageUp,                  chars: "\x1b[5~"                         }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~",     mode: Alt        }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                       }
  - { key: PageDown,                chars: "\x1b[6~"                         }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                          }
  - { key: Back,                    chars: "\x7f"                            }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                        }
  - { key: Insert,                  chars: "\x1b[2~"                         }
  - { key: Delete,                  chars: "\x1b[3~"                         }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                       }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                       }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                       }
  - { key: Left,                    chars: "\x1b[D",        mode: ~AppCursor }
  - { key: Left,                    chars: "\x1bOD",        mode: AppCursor  }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                       }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                       }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                       }
  - { key: Right,                   chars: "\x1b[C",        mode: ~AppCursor }
  - { key: Right,                   chars: "\x1bOC",        mode: AppCursor  }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                       }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                       }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                       }
  - { key: Up,                      chars: "\x1b[A",        mode: ~AppCursor }
  - { key: Up,                      chars: "\x1bOA",        mode: AppCursor  }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                       }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                       }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                       }
  - { key: Down,                    chars: "\x1b[B",        mode: ~AppCursor }
  - { key: Down,                    chars: "\x1bOB",        mode: AppCursor  }
  - { key: F1,                      chars: "\x1bOP"                          }
  - { key: F2,                      chars: "\x1bOQ"                          }
  - { key: F3,                      chars: "\x1bOR"                          }
  - { key: F4,                      chars: "\x1bOS"                          }
  - { key: F5,                      chars: "\x1b[15~"                        }
  - { key: F6,                      chars: "\x1b[17~"                        }
  - { key: F7,                      chars: "\x1b[18~"                        }
  - { key: F8,                      chars: "\x1b[19~"                        }
  - { key: F9,                      chars: "\x1b[20~"                        }
  - { key: F10,                     chars: "\x1b[21~"                        }
  - { key: F11,                     chars: "\x1b[23~"                        }
  - { key: F12,                     chars: "\x1b[24~"                        }
  - { key: F1,       mods: Shift,   chars: "\x1b[1;2P"                       }
  - { key: F2,       mods: Shift,   chars: "\x1b[1;2Q"                       }
  - { key: F3,       mods: Shift,   chars: "\x1b[1;2R"                       }
  - { key: F4,       mods: Shift,   chars: "\x1b[1;2S"                       }
  - { key: F5,       mods: Shift,   chars: "\x1b[15;2~"                      }
  - { key: F6,       mods: Shift,   chars: "\x1b[17;2~"                      }
  - { key: F7,       mods: Shift,   chars: "\x1b[18;2~"                      }
  - { key: F8,       mods: Shift,   chars: "\x1b[19;2~"                      }
  - { key: F9,       mods: Shift,   chars: "\x1b[20;2~"                      }
  - { key: F10,      mods: Shift,   chars: "\x1b[21;2~"                      }
  - { key: F11,      mods: Shift,   chars: "\x1b[23;2~"                      }
  - { key: F12,      mods: Shift,   chars: "\x1b[24;2~"                      }
  - { key: F1,       mods: Control, chars: "\x1b[1;5P"                       }
  - { key: F2,       mods: Control, chars: "\x1b[1;5Q"                       }
  - { key: F3,       mods: Control, chars: "\x1b[1;5R"                       }
  - { key: F4,       mods: Control, chars: "\x1b[1;5S"                       }
  - { key: F5,       mods: Control, chars: "\x1b[15;5~"                      }
  - { key: F6,       mods: Control, chars: "\x1b[17;5~"                      }
  - { key: F7,       mods: Control, chars: "\x1b[18;5~"                      }
  - { key: F8,       mods: Control, chars: "\x1b[19;5~"                      }
  - { key: F9,       mods: Control, chars: "\x1b[20;5~"                      }
  - { key: F10,      mods: Control, chars: "\x1b[21;5~"                      }
  - { key: F11,      mods: Control, chars: "\x1b[23;5~"                      }
  - { key: F12,      mods: Control, chars: "\x1b[24;5~"                      }
  - { key: F1,       mods: Alt,     chars: "\x1b[1;6P"                       }
  - { key: F2,       mods: Alt,     chars: "\x1b[1;6Q"                       }
  - { key: F3,       mods: Alt,     chars: "\x1b[1;6R"                       }
  - { key: F4,       mods: Alt,     chars: "\x1b[1;6S"                       }
  - { key: F5,       mods: Alt,     chars: "\x1b[15;6~"                      }
  - { key: F6,       mods: Alt,     chars: "\x1b[17;6~"                      }
  - { key: F7,       mods: Alt,     chars: "\x1b[18;6~"                      }
  - { key: F8,       mods: Alt,     chars: "\x1b[19;6~"                      }
  - { key: F9,       mods: Alt,     chars: "\x1b[20;6~"                      }
  - { key: F10,      mods: Alt,     chars: "\x1b[21;6~"                      }
  - { key: F11,      mods: Alt,     chars: "\x1b[23;6~"                      }
  - { key: F12,      mods: Alt,     chars: "\x1b[24;6~"                      }
  - { key: F1,       mods: Super,   chars: "\x1b[1;3P"                       }
  - { key: F2,       mods: Super,   chars: "\x1b[1;3Q"                       }
  - { key: F3,       mods: Super,   chars: "\x1b[1;3R"                       }
  - { key: F4,       mods: Super,   chars: "\x1b[1;3S"                       }
  - { key: F5,       mods: Super,   chars: "\x1b[15;3~"                      }
  - { key: F6,       mods: Super,   chars: "\x1b[17;3~"                      }
  - { key: F7,       mods: Super,   chars: "\x1b[18;3~"                      }
  - { key: F8,       mods: Super,   chars: "\x1b[19;3~"                      }
  - { key: F9,       mods: Super,   chars: "\x1b[20;3~"                      }
  - { key: F10,      mods: Super,   chars: "\x1b[21;3~"                      }
  - { key: F11,      mods: Super,   chars: "\x1b[23;3~"                      }
  - { key: F12,      mods: Super,   chars: "\x1b[24;3~"                      }
  - { key: NumpadEnter,             chars: "\n"                              }
